#ifndef ASCENSION_VERSION_H
#define ASCENSION_VERSION_H

#define ASCENSION_NAME "Ascension"
#define ASCENSION_VERSION "0.0.1"
#define ASCENSION_WINDOW_TITLE ASCENSION_NAME " " ASCENSION_VERSION

#endif
